/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./app/components/**/*.{ts,tsx}', './app/**/*.{ts,tsx}'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },

    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        keyframes: {
          'accordion-down': {
            from: { height: 0 },
            to: { height: 'var(--radix-accordion-content-height)' },
          },
          'accordion-up': {
            from: { height: 'var(--radix-accordion-content-height)' },
            to: { height: 0 },
          },
        },
        animation: {
          'accordion-down': 'accordion-down 0.2s ease-out',
          'accordion-up': 'accordion-up 0.2s ease-out',
        },
        'primary-dark': {
          100: '#33423d',
          200: '#2e3b37',
          300: '#293531',
          400: '#242e2b',
          500: '#1f2825',
          600: '#141a18',
          700: '#0f1412',
          800: '#0a0d0c',
          900: '#050706',
        },
        'primary-light': {
          50: '#ebecec',
          100: '#d6d9d8',
          200: '#c2c6c5',
          300: '#adb3b1',
          400: '#99a19e',
          500: '#858e8b',
          600: '#707b77',
          700: '#5c6864',
          800: '#475550',
        },
        'secondary-dark': {
          100: '#b1bcbe',
          200: '#9ea7a9',
          300: '#8a9294',
          400: '#767d7f',
          500: '#63696a',
          600: '#4f5454',
          700: '#3b3f3f',
          800: '#272a2a',
          900: '#141515',
        },
        'secondary-light': {
          50: '#f9fafb',
          100: '#f3f6f6',
          200: '#eef1f2',
          300: '#e8eded',
          400: '#e2e8e9',
          500: '#dce3e5',
          600: '#d6dfe0',
          700: '#d1dadc',
          800: '#cbd6d7',
          900: '#c5d1d3',
        },
        tertiary: {
          50: '#e7f0f2',
          100: '#cee1e6',
          200: '#b6d2d9',
          300: '#9ec3cc',
          400: '#86b4c0',
          500: '#6da5b3',
          600: '#5596a6',
          700: '#3d8799',
          800: '#24788d',
          900: '#0c6980',
        },
        accent: '#00dcb3',
        'accent-light': {
          100: '#e6fcf7',
          200: '#ccf8f0',
          300: '#b3f5e8',
          400: '#99f1e1',
          500: '#80eed9',
          600: '#66ead1',
          700: '#4de7ca',
          800: '#33e3c2',
          900: '#1ae0bb',
        },
        'accent-dark': {
          100: '#00c6a1',
          200: '#00b08f',
          300: '#009a7d',
          400: '#00846b',
          500: '#006e5a',
          600: '#005848',
          700: '#004236',
          800: '#002c24',
          900: '#001612',
        },
        dimWhite: 'rgba(255, 255, 255, 0.7)',
        dimBlue: 'rgba(9, 151, 124, 0.1)',
        textLight: '#f9fbf9',
        textDark: '#191919',
      },
      fontFamily: {
        poppins: ['Poppins', 'sans-serif'],
        sans: ['Graphik', 'sans-serif'],
        serif: ['Merriweather', 'serif'],
        montserrat: [`var(--font-montserrat)`, 'sans-serif'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      screens: {
        xs: '480px',
        ss: '620px',
        sm: '768px',
        md: '1060px',
        lg: '1200px',
        xl: '1440px',
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
